### PR TITLE
allow passing a callback to useFetch's `run` to modify init

### PR DESCRIPTION
**Pull request by phryneas**
Heyo :)

This adresses #75.

Instead of using a parameter to be spread to init, I chose for a callback function.
This has two reasons
* if `run` is just passed as an onClick handler, a React SyntheticEvent would have been passed and possibly spread on to `init`. Detecting all kinds of events would be a pain, but `typeof x === "function"` is a simple test that it is NOT an event.
* this way, existsing properties can be modified (like adding a new header) without introducing an additional dependency to something like `deep-merge`

I also split up the method definition between `deferFn`and `promiseFn` because the handling of 2 parameters vs 3 parameters was already confusing enough (sometimes props is ctrl, sometimes ctrl is ctrl).   
I think this improves readability without impacting code size too much.

Also, I reduced boolean logic at two places to better handle the `undefined` case of `defer` and `json`.

Of, and of course there's a new unit test and a bit more README :)

Looking forward to your feedback. 🙋

### CODE REVIEW

**Comment by phryneas** [comment]
Okay, now eslint should be happy, too.

**Comment by phryneas** [comment]
Okay, I've tried the failing `./node_modules/.bin/lerna run --scope '*-example' test -- --passWithNoTests --watchAll=false` locally and it's working. I have no idea what is failing there, could you take a look?

**Comment by phryneas** [comment]
Seems like the tests are generally breaking with react 16.9 and something `yarn ci` does causes the newest react version to be installed.
So nothing associated with this PR :/

**Comment by phryneas** [comment]
I opened #77 to adress the test issue. 

As I'll be gone for vacation tomorrow, I can only do any changes you request today during the day - otherwise feel free to just push any modifications to the top of my branch. (Due to #77, I fear this might take a little longer unti you get to this :/ )

**Comment by ghengeveld** [comment]
I'm very happy with where you're going with this. I'm in doubt about the callback though. I like the flexibility it provides but I still would prefer to have the option to just pass an object. We can detect a SyntheticEvent using one of the [attributes](https://reactjs.org/docs/events.html#overview) they have, such as `preventDefault`.

My preference would be:
- if function, use it to determine init
- if object and not SyntheticEvent, spread it after init
- else do nothing with init

**Comment by phryneas** [comment]
Sounds like a plan! I'll do that as soon as I'm back.

Am 10. August 2019 13:41:34 MESZ schrieb Gert Hengeveld <notifications@github.com>:
>I'm very happy with where you're going with this. I'm in doubt about
>the callback though. I like the flexibility it provides but I still
>would prefer to have the option to just pass an object. We can detect a
>SyntheticEvent using one of the
>[attributes](https://reactjs.org/docs/events.html#overview) they have,
>such as `preventDefault`.
>
>My preference would be:
>- if function, use it to determine init
>- if object and not SyntheticEvent, spread it after init
>- else do nothing with init

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by phryneas** [comment]
Okay, that should do it for the functionality. I also pushed a commit that gives `run` in the context of `useFetch` better typings.

And I added an example. But unfortunately, I can't get the examples to run - are these examples currently runnable? It seems as if it can't parse the jsx tokens in `packages/react-async/Async.jsx`.

**Comment by phryneas** [comment]
I just rebased this on master and it seems to fail again - I guess this is due to some change on master?

**Comment by ghengeveld** [comment]
Yes the introduction of React v16.9 is causing some issues. On CircleCI things work fine but on Travis they fail. I suspect updating the examples to 16.9 might help.

**Comment by ghengeveld** [comment]
That seems to work. Should be [fixed now](https://travis-ci.org/ghengeveld/react-async/builds/572766919).

**Comment by phryneas** [comment]
Okay, tests are now passing.
Also, I found the problem with my example: my IDE had imported `useFetch` from `react-async/src` instead of `react-async` and I had missed that. 
Now everything should be good.

**Comment by ghengeveld** [comment]
Released in [v8.0.0](https://github.com/ghengeveld/react-async/releases/tag/v8.0.0)

**Comment by ghengeveld** [comment]
@all-contributors please add @phryneas for ideas

**Pull request merged**
