### PR TITLE
Fix resolved only displaying after rejected defer when persisted

### LINKED ISSUE #4: old data remains rendered after update with error
I have this peace of code:

```
const ResultSection = ({ text }) => (
    <Async watch={text} promiseFn={() => search(text)}>
        <Async.Loading>Loading...</Async.Loading>
        <Async.Resolved>
            {(data) => (<Result data={data}/>)}
        </Async.Resolved>
        <Async.Rejected>{(error) => `Something went wrong: ${error.message}`}</Async.Rejected>
    </Async>
);
```

the `<Result data={data}/>` component remains rendered with the old data after rerunning `promiseFn()` with new `text`  producing an error, resulting in

```
<Result data={data}/>
Something went wrong: ${error.message}
```

I can prevent rendering the old `<Result data={data}/>` component using this code:

```
...
<Async.Resolved>
      {(data, { error }) => {return error ? null : (
                <Result data={data} />
       )}}
</Async.Resolved>
...
```

but I think this is a workaround and the old `<Result data={data}/>` component should disappear without this explicit check on error.

### PR DESCRIPTION
**Pull request by byCedric**
Fixes #4 

@norama I'm so sorry if I stole your thunder! I had to wait for one of our Macs to upgrade, and I recently discovered this library. So I thought, why not spend it usefully 😄

Hope this helps!

### CODE REVIEW

**Comment by ghengeveld** [comment]
Released in [3.7.1](https://github.com/ghengeveld/react-async/releases/tag/v3.7.1)

Thanks a lot for contributing! 🎉

**Comment by ghengeveld** [comment]
Be aware I also released 3.7.2 which fixes a [related bug](https://github.com/ghengeveld/react-async/issues/1).

**Comment by byCedric** [comment]
Sounds great, thanks for the updates! 😁

**Comment by ghengeveld** [comment]
@all-contributors please add @byCedric for code

**Pull request merged**
