### PR TITLE
Add type definitions for TypeScript (fixes #10)

### LINKED ISSUE #10: Typings
Hello,

is there a plan for official typescript support?

Thanks.

### PR DESCRIPTION
**Pull request by ghengeveld**

### CODE REVIEW

**Comment by tomshane** [comment]
If you would like to have a look, here is my current typings file. On my current setup (TS 3.1.4), generics seem to work for base Async component. For helper components, I didn't find a way how to improve typing.

```
declare module "react-async"
{
  import * as React from "react";

  interface AsyncProps<T> {
    promiseFn?: (props: object) => Promise<T>;
    deferFn?: (...args, props: object) => Promise<T>;
    watch?: any;
    initialValue?: T;
    onResolve?: (data: T) => void;
    onError?: (error: Error) => void;
    children?: AsyncChildren<T>;
  }

  interface AsyncState<T> {
    initialValue: T,
    data: T,
    error: Error,
    isLoading: boolean,
    startedAt: Date,
    finishedAt: Date,
    cancel: () => void,
    run: (...args) => Promise<T>,
    reload: () => void,
    setData: (data: T, callback?: () => void) => T,
    setError: (error: Error, callback?: () => void) => Error
  }

  function createInstance<T>(defaultProps?: AsyncProps<T> = {}): Async<T>;

  type AsyncChildren<T> = ((state: AsyncState<T>) => React.ReactNode) | React.ReactNode;

  class Async<T> extends React.Component<AsyncProps<T>, AsyncState<T>> {
    static Pending: React.FunctionComponent<{ children?: AsyncChildren, persist?: boolean }>;
    static Loading: React.FunctionComponent<{ children?: AsyncChildren, initial?: boolean }>;
    static Resolved: React.FunctionComponent<{ children?: AsyncChildren, persist?: boolean }>;
    static Rejected: React.FunctionComponent<{ children?: AsyncChildren, persist?: boolean }>;
  }

  export default createInstance;
}
```

**Comment by ghengeveld** [comment]
Looks good 👍 I'll update my PR.
Shouldn't most of the state values be optional?

```ts
interface AsyncState<T> {
  initialValue?: T
  data?: T
  error?: Error
  isLoading: boolean
  startedAt?: Date
  finishedAt?: Date
  cancel: () => void
  run: (...args) => Promise<T>
  reload: () => void
  setData: (data: T, callback?: () => void) => T
  setError: (error: Error, callback?: () => void) => Error
}
```

**Comment by tomshane** [comment]
Yes, your `AsyncState` is the correct one.

**Comment by ghengeveld** [comment]
I've pushed the latest changes. VS Code was complaining about the `deferFn?: (...args, props: object)` because rest params aren't supported in that position by TypeScript, so I just removed the props param and have the ...args match it.

Also VS Code was complaining about the generic type T not being accessible to static members of Async. Maybe it works regardless?

Could you check if this works?

**Comment by tomshane** [comment]
I placed the index.d.ts file into `node_modules/react-async` folder and VS Code didn't complain at all. No errors in console while compiling either. So here, everything look great.

**Comment by ghengeveld** [comment]
Alright, I'm merging it then. We can always make tweaks later.

**Comment by ghengeveld** [comment]
Published in [v3.8.1](https://github.com/ghengeveld/react-async/tree/v3.8.1)

**Comment by ghengeveld** [comment]
Hey @tomshane, I've been looking at this again and I'm not happy with the way the static members are defined. Their type signature is obviously broken because a static member cannot access the parent class' generic type. I've been fiddling around with it all day but still have not found a solution. So I had to ask: https://stackoverflow.com/questions/53564005/correct-type-definition-for-a-react-class-with-static-member-components

Maybe you can take a look at it?

**Comment by tomshane** [comment]
Yea, I was trying before, but I gave up, because I couldn't make it work. That's why I left the helper components non-generic in my draft. I have found this: https://github.com/Microsoft/TypeScript/issues/24018, so it seems it is not supported in the current TS.

**Comment by ghengeveld** [comment]
Well they don't have to reference the class generic, they can have their own. I just haven't found a way to do that yet.

**Comment by tomshane** [comment]
I don't know if that's what you have in mind, but I've tried this:

```
declare class Async<T> extends React.Component<AsyncProps<T>, AsyncState<T>> {  
  static Pending: <T>(props: { children?: AsyncChildren<T>; persist?: boolean }) => JSX.Element;
  static Loading:  <T>(props: { children?: AsyncChildren<T>; initial?: boolean }) => JSX.Element;
  static Resolved: <T>(props: { children?: AsyncChildren<T>; persist?: boolean }) => JSX.Element;
  static Rejected: <T>(props: { children?: AsyncChildren<T>; persist?: boolean }) => JSX.Element;
}
export default Async;
```
This way I was able to use helper components without an issue. However, the generic type argument won't be inferred, so the usage must be either:
```
<Async.Resolved>
  {(data: MyData) => { ... }}
</Async.Resolved>
```
or:

```
<Async.Resolved<MyData>>
  {(data) => { ... }}
</Async.Resolved>
```

**Comment by ghengeveld** [comment]
@all-contributors please add @tomshane for review

**Comment by ghengeveld** [comment]
@all-contributors please add @ghengeveld for code, review, question, blog, doc, design, example, financial, infra, maintenance

**Pull request merged**
